explore/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('hotel',views.hotel,name='hotel'),
    
    path('destinations',views.destinations,name='destinations'),

    path('packages',views.packages,name='packages'),
    
    path('booking/', views.booking, name='booking'),
   
    path('search',views.searchDestinations,name='search'),

    path('dynamic/<int:destinations_id>/',views.dynamic,name='dynamic'),

    path('pack2/<int:package2_id>/',views.package2, name='pack2'),

    path('viewhotels/<int:hotels_id>/',views.view_hotels,name='viewhotels'),

    path('payment/',views.payment.as_view(),name='payment'),
    path('charge/',views.charge,name='charge'),
    path('error/',views.error,name='error'),
    path('receipt/', views.receipt, name='receipt'),

    path('cancel_book/<int:booking_id>/', views.cancel_booking, name='cancel_book'),
    path('booking_list/',views.booking_list,name='booking_list')
     
]

hotel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('submit_hotel/', views.submit_hotel, name='submit_hotel'),
    path('view_submitted_hotels/', views.view_submitted_hotels, name='view_submitted_hotels'),
    path('approve_hotel/<int:pk>/', views.approve_hotel, name='approve_hotel'),
    path('reject_hotel/<int:pk>/', views.reject_hotel, name='reject_hotel'),

    path('hotelhome',views.hotel_home,name='hotelhome'),

    path('addhotel/',views.add_hotel,name='admin_hotel'),
    path('hotel_admin',views.hotel_admin,name='hotel_admin'),
    path('update_hotel/<int:hotel_id>/', views.update_hotel, name='update_hotel'),
    path('delete_hotel/<int:hotel_id>/', views.delete_hotel, name='delete_hotel'),
]

voyage/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('explore.urls')),
    path('',include('authentication.urls')),
    path('',include('intro.urls')),
    path('',include('admins.urls')),
    path('',include('hotel.urls')),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

explore/models.py
from django.db import models
from django.contrib.auth.models import User

class Destinations(models.Model):
    name=models.CharField(max_length=100)
    img=models.ImageField(upload_to='destinations')
    desc=models.TextField()
    
class Hotel(models.Model):
    owner = models.TextField(default='Unknown')
    name=models.CharField(max_length=100)
    img=models.ImageField(upload_to='hotel')
    desc=models.TextField()
    price=models.IntegerField()
    rating=models.PositiveIntegerField()
    license_verified = models.BooleanField(default=False)
    license_number=models.PositiveIntegerField()
    submitted = models.BooleanField(default=False)
   
    def __str__(self):
        return self.name

class Packages(models.Model):
    name=models.CharField(max_length=100)
    img=models.ImageField(upload_to='packages')
    img1=models.ImageField(upload_to='packages')
    desc=models.TextField()
    desc1=models.TextField()
    price=models.IntegerField()
    price1=models.IntegerField()
   
class Booking(models.Model):
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    phonenumber=models.CharField(max_length=10)
    email=models.CharField(max_length=200)
    checkin=models.DateField()
    checkout=models.DateField()
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    package = models.ForeignKey(Packages, on_delete=models.CASCADE)

    GUESTS_CHOICES = (
        (1, '1 guest'),
        (2, '2 guests'),
        (3, '3 guests'),
        (4, '4 guests'),
        (5, '5 guests'),
    )

    guests = models.PositiveIntegerField(choices=GUESTS_CHOICES)
    
    AC = 'AC'
    NON_AC = 'Non-AC'
    SINGLE_BED = 'Single Bed'
    DOUBLE_BED = 'Double Bed'

    ROOM_TYPE_CHOICES = (
        (AC, 'AC'),
        (NON_AC, 'Non-AC'),
        (SINGLE_BED, 'Single Bed'),
        (DOUBLE_BED, 'Double Bed'),
    )

    room_type = models.CharField(max_length=100, choices=ROOM_TYPE_CHOICES)
    canceled = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.firstname} {self.lastname}"

class Dynamic(models.Model):
    desc1=models.TextField()
    desc2=models.TextField()
    img=models.ImageField(upload_to='dynamic')
    img1=models.ImageField(upload_to='dynamic')
    img2=models.ImageField(upload_to='dynamic')
    img3=models.ImageField(upload_to='dynamic')
    img4=models.ImageField(upload_to='dynamic')
    img5=models.ImageField(upload_to='dynamic')

    def __str__(self):
        return self.desc1

class Package2(models.Model):
    desc1=models.TextField()
    desc2=models.TextField()
    desc3=models.TextField()
    img=models.ImageField(upload_to='package2')
    img1=models.ImageField(upload_to='package2')
    img2=models.ImageField(upload_to='package2')
    name=models.CharField(max_length=100)
    hotelimg=models.ImageField(upload_to='package2')
    hotelname=models.CharField(max_length=50)
    hoteldesc=models.TextField()

class ViewHotels(models.Model):
    img=models.ImageField(upload_to='viewhotels')
    img1=models.ImageField(upload_to='viewhotels')
    img2=models.ImageField(upload_to='viewhotels')
    name=models.CharField(max_length=100)
    name1=models.CharField(max_length=100)
    name2=models.CharField(max_length=100)
    hotelname=models.CharField(max_length=100)
    desc=models.TextField()
    desc1=models.TextField()
    desc2=models.TextField()
    review=models.TextField()
    review1=models.TextField()
    review2=models.TextField()
    rating=models.PositiveIntegerField()
    rating1=models.PositiveIntegerField()
    rating2=models.PositiveIntegerField()
    price=models.IntegerField()
    price1=models.IntegerField()
    price2=models.IntegerField()

# Create your models here.

hotel/models.py
from django.db import models

# Create your models here.

explore/forms.py
from django import forms
from .models import Booking,Hotel, Packages

from django.forms.widgets import DateInput
from django.utils import timezone

class DateInput(forms.DateInput):
    input_type='date'

class BookingForm(forms.ModelForm):
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.all(), empty_label="-- Select a Hotel --")
    package = forms.ModelChoiceField(queryset=Packages.objects.all(), empty_label="-- Select a Package --")
    class Meta:
        model=Booking
        fields = '__all__'
      
        widgets = {
            'checkin': DateInput(attrs={'type': 'date', 'min': timezone.now().date().isoformat()}),
            'checkout': DateInput(attrs={'type': 'date', 'min': timezone.now().date().isoformat()}),
        }
        
        labels={
            'firstname':"First Name",
            'lastname':"Last Name",
            'phonenumber':"Phone Number",
            'email':"Email",
            'checkin':"Check-in",
            'checkout':"Check-out",
            'guests':"No. of Guests",
            'room_type':"Room Type",
        }

class CancelBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['canceled']
        
        

hotel/forms.py
from django import forms
from explore.models import Hotel

class HotelSubmissionForm(forms.ModelForm):

    class Meta:
        model = Hotel
        exclude = ['owner','license_verified']

    def __init__(self, *args, **kwargs):
        super(HotelSubmissionForm, self).__init__(*args, **kwargs)
        self.fields['license_number'].widget.attrs['placeholder'] = 'Enter License Number'
        self.fields['desc'].widget.attrs['style'] = 'width: 100%;'
     
    submitted = forms.BooleanField(
        label='Do you want to submit?',
        required=False,  # Since it's a checkbox, it can be optional
        widget=forms.CheckboxInput(attrs={'class': 'checkbox-input'}),
    )
        

explore/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BookingForm, CancelBookingForm
from django.contrib import messages


from .models import Hotel
from .models import ViewHotels
from .models import Destinations
from .models import Dynamic
from .models import Packages,Package2
from .forms import BookingForm
from .models import Booking

from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from xhtml2pdf import pisa
from decimal import Decimal  

from django.conf import settings
from django.views.generic import TemplateView
import stripe


#destinations
def destinations(request):
    destinations=Destinations.objects.all()
    return render(request,'base/destinations.html',{'destinations':destinations})

def dynamic(request,destinations_id):
    dynamics=get_object_or_404(Dynamic,pk=destinations_id)
    return render(request,'base/dynamic.html',{'dynamics':dynamics})


def searchDestinations(request):
    if request.method=='GET':
            query=request.GET.get('query')
            if query:
                destinations=Destinations.objects.filter(name__icontains=query)
                return render(request,'base/search.html',{'destinations':destinations})
            else:
                print("No Destinations")
                return render(request,'base/search.html',{})


#packages
def packages(request):
    packages=Packages.objects.all()
    return render(request,'base/packages.html',{'packages':packages})

def package2(request,package2_id):
    package2=get_object_or_404(Package2,pk=package2_id)
    return render(request,'base/pack2.html',{'package2':package2})


#hotels
def hotel(request):
    hotel = Hotel.objects.filter(license_verified = True)
    return render(request,'base/hotel.html',{'hotel':hotel})

def view_hotels(request,hotels_id):
    hotels=get_object_or_404(ViewHotels,pk=hotels_id)
    return render(request,'base/viewhotels.html',{'hotels':hotels})


#booking
def booking(request):
    hotels = Hotel.objects.all()
    packages = Packages.objects.all()
   

    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)  
            selected_hotel = form.cleaned_data['hotel']
            selected_package = form.cleaned_data['package']
            total_cost = selected_hotel.price + selected_package.price
            booking.total_cost = total_cost
            booking.save()      
            return redirect('payment')
    else:
        form = BookingForm()

    context = {
        'form': form,
        'hotels': hotels,
        'packages': packages,
       
    }

    return render(request, 'base/booking.html', context)         

class payment(TemplateView):
    template_name='base/payment.html'

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY 
        return context

stripe.api_key = settings.STRIPE_SECRET_KEY     
def charge(request):
    publishable_key = settings.STRIPE_PUBLISHABLE_KEY
    return render(request, 'base/charge.html', {'key': publishable_key})

    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            charge = stripe.Charge.create(
                amount=500,  # Make sure to replace this with the actual amount
                currency='inr',
                description='Payment Gateway',
                source=token,
            )
            return render(request, 'base/charge.html')
        except stripe.error.CardError as e:
            return render(request, 'base/error.html', {'error': e})
        except Exception as e:
            return render(request, 'base/error.html', {'error': e})
    return redirect('payment')
    

def error(request):
    return render(request,'base/error.html')


#payment receipt
def receipt(request):
    receipt = Booking.objects.last()

    # Calculate package and hotel prices
    package_price = receipt.package.price if receipt.package else Decimal('0.00')
    hotel_price = receipt.hotel.price if receipt.hotel else Decimal('0.00')
    tax = (package_price + hotel_price) * Decimal('0.07')  # Assuming tax is 7% of the total

    template_path = 'base/receipt.html'
    context = {
        'firstname': receipt.firstname,
        'lastname': receipt.lastname,
        'phonenumber': receipt.phonenumber,
        'email': receipt.email,
        'id': receipt.id,
        'checkin': receipt.checkin,
        'checkout': receipt.checkout,
        'guests': receipt.guests,
        'package': receipt.package,
        'hotel': receipt.hotel,
        'room_type': receipt.room_type,
        'package_price': package_price,
        'hotel_price': hotel_price,
        'tax': tax,
        'total_with_tax': package_price + hotel_price + tax,
    }
    

    template = get_template(template_path)
    html = template.render(context)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename="{receipt.package}_trip_bill.pdf"'

    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('Error generating PDF', status=500)
    return response


#cancellation
def cancel_booking(request, booking_id):
    booking = Booking.objects.get(id=booking_id)    
    if request.method == 'POST':
        form = CancelBookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('booking_list')
    else:
        form = CancelBookingForm(instance=booking)
    return render(request, 'base/cancel_book.html', {'form': form, 'booking': booking})


def booking_list(request):
    # if not request.user.is_authenticated:
    #     messages.warning(request, 'Please log in to view your bookings.')
    #     return redirect('user_login')
    bookings = Booking.objects.filter(canceled=False)
    return render(request, 'base/booking_list.html', {'bookings': bookings})

hotel/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import HotelSubmissionForm
from django.contrib import messages
from explore.models import Hotel
from django.contrib.auth.decorators import login_required

def submit_hotel(request):
    if request.method == 'POST':
        form = HotelSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            # Set the owner before saving the form
            form.instance.owner = request.user
            # Mark the hotel as submitted for approval
            # form.instance.submitted = True
            form.save()
            messages.success(request, 'Hotel submitted successfully. Waiting for approval.')
            return redirect('index') # Redirect to the home page or a thank-you page
    else:
        form = HotelSubmissionForm()
    return render(request, 'base/submit_hotel.html', {'form': form})

def view_submitted_hotels(request):
    if request.user.is_superuser:
        hotels = Hotel.objects.filter(license_verified = False)
        return render(request, 'base/view_submitted_hotels.html', {'hotels': hotels})
    else:
        return redirect('hotelhome') # Redirect to the home page

def approve_hotel(request, pk):
    if request.user.is_superuser:
        hotel = Hotel.objects.get(id=pk)
        hotel.license_verified = True
        hotel.save()
        # messages.success(request, 'Hotel approved successfully.')
        return redirect('view_submitted_hotels')
    else:
        return redirect('index') # Redirect to the home page

def reject_hotel(request, pk):
    if request.user.is_superuser:
        hotel = Hotel.objects.get(id=pk)
        hotel.delete()
        messages.success(request, 'Hotel rejected successfully.')
        return redirect('view_submitted_hotels')
    else:
        return redirect('index') # Redirect to the home page
    

def hotel_home(request):
    return render(request,'base/hotel_home.html')


#HOTELS
def hotel_admin(request):
    hotel=Hotel.objects.all()
    return render(request,'base/hotel_admin.html',{'hotel':hotel})

def add_hotel(request):
    if request.method == 'POST':
        name = request.POST.get('hotel_name')
        img = request.FILES.get('hotel_img')
        desc = request.POST.get('hotel_desc')
        price = request.POST.get('hotel_price')
        rating = request.POST.get('hotel_rating')
        license_number=request.POST.get('hotel_license')
        Hotel.objects.create(name=name,img=img, desc=desc,price=price,rating=rating,license_number=license_number)
        if 'add_another' in request.POST:
            
            return redirect('admin_hotel') 
        else:
            
            return redirect('hotel_admin') 

    return render(request, 'base/admin_hotel.html')
    
@login_required
def update_hotel(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    if request.method == 'POST':
        hotel.name = request.POST.get('hotel_name')
        hotel.img=request.FILES.get('hotel_img')
        hotel.desc=request.POST.get('hotel_desc')
        hotel.price = request.POST.get('hotel_price')
        hotel.rating = request.POST.get('hotel_rating')
        hotel.license = request.POST.get('hotel_license')
        hotel.save()
        return redirect('hotel_admin')
    return render(request, 'base/update_hotel.html', {'hotel': hotel})

@login_required
def delete_hotel(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    if request.method == 'POST':

        hotel.delete()
        return redirect('hotel_admin')
    return render(request, 'base/hotel_admin.html', {'hotel': hotel})

explore/templates/base/booking.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Booking Form</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'Css\booking.css' %}"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>

    <style>
      body {
        margin: 0;

        background-image: linear-gradient(
            rgba(0, 0, 0, 0.363),
            rgba(5, 5, 5, 0.5)
          ),
          url(/staticfiles/images/booking.jpg);
        background-attachment: fixed;
        background-size: 100% 100%;
        background-repeat: no-repeat;
      }  
      footer{
        bottom:-250%;
      }
      .login-container {
        margin-top: 20px;
        padding: 15px;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
      }
      
      .login-message {
        color: red; 
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 10px;
        text-align:center;
      }
      
      .login-button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 16px;
        color: #fff;
        background-color: #007bff; 
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        margin-left:140px;
      }
      
      .login-button:hover {
        background-color: #0056b3; 
      }
    </style>
  </head>
  <body>
      
      {% block contents %}   
        <h1>HOTEL BOOKING</h1>
        <div class="container">
          {% if user.is_authenticated %}
            <form action="" method="POST">
                {% csrf_token %}
                
              
                {{ form.firstname.label_tag }} {{ form.firstname }}
                {{ form.lastname.label_tag }} {{ form.lastname }}
                
                
                {{ form.phonenumber.label_tag }} {{ form.phonenumber }}
                {{ form.email.label_tag }} {{ form.email }}
                
                
                {{ form.checkin.label_tag }} {{ form.checkin }}
                {{ form.checkout.label_tag }} {{ form.checkout }}
                
                
                {{ form.guests.label_tag }} {{ form.guests }}
                
                
                {{ form.room_type.label_tag }} {{ form.room_type }}
                
              
                <label for="id_hotel">Select a Hotel:</label>
                <select id="id_hotel" name="hotel">
                    <option value="">-- Select a Hotel --</option>
                    {% for hotel in hotels %}
                        <option value="{{ hotel.id }}">{{ hotel.name }}</option>
                    {% endfor %}
                </select>
                
              
                <label for="id_package">Select a Package:</label>
                <select id="id_package" name="package">
                    <option value="">-- Select a Package --</option>
                    {% for package in packages %}
                        <option value="{{ package.id }}">{{ package.name }}</option>
                    {% endfor %}
                </select>
              
                <button type="submit">MAKE PAYMENT</button>
              
            </form>
          {% else %}
            <div class="login-container">
              <p class="login-message">Please log in to fill your booking.</p>
              <a href="{% url 'user_login' %}" class="login-button">Log In</a>
            </div>
          {% endif %}
       
        </div>
      
      {% endblock %}

      <footer>
        <div class="footer-container">
          <div class="footer-section">
            <h3>Contact Us</h3>
            <p>
              BonVoyage Travel Agency<br />
              123 Main Street, Kochi,<br />
              India<br />
              Phone: +1 123-456-7890<br />
              <a href="mailto:info@bonvoyage.com">Email: info@bonvoyage.com</a>
            </p>
          </div>
  
          <div class="footer-section">
            <h3>Quick Links</h3>
            <ul>
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'destinations' %}">Destinations</a></li>
              <li><a href="{% url 'hotel' %}">Hotels</a></li>
              <li><a href="{% url 'submit_hotel' %}">Add Hotel</a></li>
              <li><a href="{% url 'packages' %}">Packages</a></li>
              <li><a href="{% url 'blog' %}">Blog</a></li>
              <li><a href="{% url 'create_comment' %}">Reviews</a></li>
              <li><a href="{% url 'aboutus' %}">About Us</a></li>
              <li><a href="{% url 'contactus' %}">Contact Us</a></li>
            </ul>
          </div>

          <div class="footer-section">
            <h3>Our Services</h3>
            <ul>
                <li><a href="{% url 'booking' %}">Booking</a></li>
                <li><a href="{% url 'booking_list' %}">Booking Lists</a></li>
            </ul>
          </div>
  
          <div class="footer-section">
            <h3>Stay Connected</h3>
            <ul class="social-media">
              <li>
                <a href="https://www.facebook.com/login/"><i class="fab fa-facebook"></i></a>
              </li>
              <li>
                <a href="https://twitter.com/i/flow/login"><i class="fab fa-twitter"></i></a>
              </li>
              <li>
                <a href="https://www.instagram.com/accounts/login/?hl=en"><i class="fab fa-instagram"></i></a>
              </li>
              <li>
                <a href="https://in.linkedin.com/"><i class="fab fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
        </div>
  
        <div class="footer-bottom">
          <p>
            &copy; 2023 BonVoyage. All rights reserved. |
            <a href="#">Privacy Policy</a> | <a href="#">Terms and Conditions</a>
          </p>
        </div>
      </footer>
  </body>
</html>




            
              

explore/templates/base/cancel_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancel Booking</title>
    <style>
        body {
            background-image: linear-gradient(
                rgba(0, 0, 0, 0.363),
                rgba(5, 5, 5, 0.5)
              ),
              url(/staticfiles/images/booking.jpg);
            background-attachment: fixed;
            background-size: 100% 100%;
            background-repeat: no-repeat;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .cancel-container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            text-align: center;
          
            
        }


        .cancel-message {
            color: #6b7280;
            margin-bottom: 20px;
        }

        .free-cancel-info {
            color: #34d399;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .reason-dropdown {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .action-buttons {
            display: flex;
            justify-content: space-around;
            margin-top: 20px;
        }

        .cancel-button,
        .keep-button {
            background-color: #e53e3e;
            color: #ffffff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .cancel-button:hover,
        .keep-button:hover {
            background-color: #c53030;
        }

        .back-link {
            color: #3490dc;
            text-decoration: none;
            display: block;
            margin-top: 10px;
        }

        .back-link:hover {
            text-decoration: underline;
        }
        button[type="submit"] {
            background-color: red;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        
       
    </style>
</head>

<body>
    <div class="cancel-container">

        <h1 class="cancel-message">Cancel Your Booking</h1>
        <p class="cancel-message">You have the option for free cancellation!</p>
        <p class="free-cancel-info">Free Cancellation within 150 days</p>
        <p class="free-cancel-info">Refund will be processed within 5 business days</p>
        <label for="reason" class="cancel-message">Select Reason for Cancellation:</label>
        <select id="reason" class="reason-dropdown" required>
            <option value="" disabled selected>-- Select a reason --</option>
            <option value="change_of_plans">Change of plans</option>
            <option value="financial_issues">Financial issues</option>
            <option value="personal_emergency">Personal emergency</option>
            <option value="other">Other</option>
        </select>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="action-buttons">
                <button type="submit">Cancel Booking</button>
               
            </div> 
        </form>
        
        <a href="{% url 'booking_list' %}" class="back-link">Go back to Booking Details</a>
    </div>
</body>

</html>

explore/templates/base/charge.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travel Booking Confirmation</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'Css/Charge.css' %}"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
</head>
<body>
    
    <div class="container">
        <h1>Travel Booking Confirmation</h1>
        <p>Thank you for booking your dream getaway with us!</p>
        <div class="success-icon">&#10004;</div>
        <p class="confirmation-message">Your booking has been successfully confirmed.</p>
        
        <div class="back-link">
            <a href="/">Back to Home</a>
        </div>

        <div class="download-button">
          <a href="{% url 'receipt'%}">
            <button>Download Invoice</button>
          </a>
        </div>
    </div>

    <footer>
        <div class="footer-container">
          <div class="footer-section">
            <h3>Contact Us</h3>
            <p>
              BonVoyage Travel Agency<br />
              123 Main Street, Kochi,<br />
              India<br />
              Phone: +1 123-456-7890<br />
              <a href="mailto:info@bonvoyage.com">Email: info@bonvoyage.com</a>
               
            </p>
          </div>
    
          <div class="footer-section">
            <h3>Quick Links</h3>
            <ul>
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'destinations' %}">Destinations</a></li>
              <li><a href="{% url 'hotel' %}">Hotels</a></li>
              <li><a href="{% url 'submit_hotel' %}">Add Hotel</a></li>
              <li><a href="{% url 'packages' %}">Packages</a></li>
              <li><a href="{% url 'blog' %}">Blog</a></li>
              <li><a href="{% url 'create_comment' %}">Reviews</a></li>
              <li><a href="{% url 'aboutus' %}">About Us</a></li>
              <li><a href="{% url 'contactus' %}">Contact Us</a></li>
            </ul>
          </div>

          <div class="footer-section">
            <h3>Our Services</h3>
            <ul>
                <li><a href="{% url 'booking' %}">Booking</a></li>
                <li><a href="{% url 'booking_list' %}">Booking Lists</a></li>
            </ul>
          </div>
    
          <div class="footer-section">
            <h3>Stay Connected</h3>
            <ul class="social-media">
              <li>
                <a href="https://www.facebook.com/login/"><i class="fab fa-facebook"></i></a>
              </li>
              <li>
                <a href="https://twitter.com/i/flow/login"><i class="fab fa-twitter"></i></a>
              </li>
              <li>
                <a href="https://www.instagram.com/accounts/login/?hl=en"><i class="fab fa-instagram"></i></a>
              </li>
              <li>
                <a href="https://in.linkedin.com/"><i class="fab fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
        </div>
    
        <div class="footer-bottom">
          <p>
            &copy; 2023 BonVoyage. All rights reserved. |
            <a href="#">Privacy Policy</a> | <a href="#">Terms and Conditions</a>
          </p>
        </div>
    </footer>  
</body>
</html>
  
  